[[carousels]]
  banner = "https://nebula-blog.azureedge.net/nebula-blog/TTL01.png"
  description = "图数据库 Nebula Graph TTL 特性"
  link = "/cn/posts/clean-stale-data-with-ttl-in-nebula-graph/"
[[carousels]]
  banner = "https://nebula-blog.azureedge.net/nebula-blog/Action01.png"
  description = "使用 Github Action 进行前端自动化发布"
  link = "/cn/posts/github-action-automating-project-process/"