baseurl = "http://localhost:1313/"
title = "Nebula Graph  - An Open Source, Distributed and High Performant Graph Database"
theme = "creative"
googleAnalytics = ""
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
################ init language Config ################
  [languages.default]
    contentDir = "content/en"
