################ 中文配置 ################
contentDir = "content/cn"
[params]
  # You can use Markdown syntax for urls [text](//url.to/source) for
  # most longer texts.

  # All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # All projects of the portfolio are defined in their own files.
  # You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
  # folder into the 'data' directory at the root of this Hugo site.
  # For more information take a look at the README.

  # To provide some metadata for search engines feel free to add some
  # information about you and your website.
  description = "水平扩展特性，强数据一致性，高可用，类SQL查询语言。Nebula让你洞察数据之间的联系。赶快免费使用它吧。"
  name = "Nebula Graph"

  # The path must be relative to the static folder
 
  favicon = "favicon.ico"
  blogTitle = "Nebula Graph 博客"
  postsTitle = "最新 Nebula Graph 博文"
  readAll ="阅读全文"

  backBlogs = "返回到博客页"

  # Navigation
  [params.navigation]
    brand = "NebulaGraph"

    [[params.navigation.links]]
      title = "应用场景"
        [[params.navigation.links.case]]
          title = "实时推荐"
          link = "/real-time-recommendation/"
        [[params.navigation.links.case]]
          title = "金融风控"
          link = "/fraud-detection/"
        [[params.navigation.links.case]]
          title = "网络安全"
          link = "/cyber-security/"
        [[params.navigation.links.case]]
          title = "知识图谱"
          link = "/ai-and-machine-learning/"
    [[params.navigation.links]]
      title = "文档"
      link = "https://docs.nebula-graph.com.cn/"
      target = "_blank"
    [[params.navigation.links]]
      title = "博客"
      link = "/posts"
      # [[params.navigation.links.links]]
      # 	title = "Use cases"
    # [[params.navigation.links]]
    # 	title = "Customers"
    [[params.navigation.links]]
      title = "论坛"
      link = "https://discuss.nebula-graph.com.cn/"
      target = "_blank"
    [[params.navigation.links]]
      title = "公司简介"
      [[params.navigation.links.case]]
        title = "媒体报道"
        link = "/news"
      [[params.navigation.links.case]]
        title = "联系我们"
        link = "mailto:info@vesoft.com"
    [[params.navigation.links]]
      pic = "language120x120.png"
        [[params.navigation.links.links]]
          title = "English"
          link = "/en/"
        [[params.navigation.links.links]]
          title = "中文"
          link = "/cn/"
    [[params.navigation.links]]
      title = "Nebula Studio"
      link = "https://github.com/vesoft-inc/nebula-web-docker"
      calss= "navbar-right"
      onclick = "gtag('event', 'Button Click', { event_category: 'Engagement', event_label: 'Nebula Studio'})"
      target = "_blank"

  # Hero section
  [params.header]
    # To change the background of the header section, replace the 'header.jpg' at './static/img' with your own.
    slogan     = "一个可靠的分布式、线性扩容、性能高效的图数据库"
    subtitle   = "世界上唯一能够容纳千亿个顶点和万亿条边，并提供毫秒级查询延时的图数据库解决方案"
    buttonText = "开始尝试"
    downloadText = "前往 GitHub"
    githubLink = "https://github.com/vesoft-inc/nebula/blob/master/README-CN.md"
    link = "https://docs.nebula-graph.com.cn/manual-CN/1.overview/2.quick-start/1.get-started/"

  # Footer section
  [params.footer]
    name = "contact_us"
    [params.footer.social]
      title = "关注我们"
      [[params.footer.social.links]]
          title = "Twitter"
          pic = "twitter.png"
          class = "icon fa fa-twitter"
          link = "https://twitter.com/NebulaGraph"
          target = "_blank"
      [[params.footer.social.links]]
          title = "LinkedIn"
          pic = "linkedin.png"
          class = "icon fa fa-linkedin"
          link = "https://www.linkedin.com/company/vesoft-nebula-graph/"
          target = "_blank"
      [[params.footer.social.links]]
          title = "YouTube"
          pic = "youtube.png"
          class = "icon fa fa-youtube"
          link = "https://www.youtube.com/channel/UC73V8q795eSEMxDX4Pvdwmw"
          target = "_blank"
      [[params.footer.social.links]]
          title = "FaceBook"
          pic = "facebook.png"
          class = "icon fa fa-facebook"
          link = "https://www.facebook.com/NebulaGraph/"
          target = "_blank"
      [[params.footer.social.links]]
          title = "微博"
          pic = "weibo.png"
          class = "icon fa fa-weibo"
          link = "https://weibo.com/nebulagraph"
          target = "_blank"
      [[params.footer.social.links]]
          title = "微信公众号"
          class = "icon fa fa-wechat"
          pic = "gongzhonghao.png"
          id = "#myGongzhonghaoModal"
          target = "_blank"

    [[params.footer.community]]
      title = "社区"
      [[params.footer.community.links]]
          title = "GitHub"
          pic = "github.png"
          link = "https://github.com/vesoft-inc/nebula"
          target = "_blank"
      [[params.footer.community.links]]
          title = "论坛"
          pic = "forum.png"
          link = "https://discuss.nebula-graph.com.cn/"
          target = "_blank"
      [[params.footer.community.links]]
          title = "Slack"
          pic = "slack.png"
          link = "https://join.slack.com/t/nebulagraph/shared_invite/enQtNjIzMjQ5MzE2OTQ2LTM0MjY0MWFlODg3ZTNjMjg3YWU5ZGY2NDM5MDhmOGU2OWI5ZWZjZDUwNTExMGIxZTk2ZmQxY2Q2MzM1OWJhMmY#"
          target = "_blank"
    [[params.footer.company]]
      title = "公司"
      [[params.footer.company.links]]
          title = "关于"
          link = "https://github.com/vesoft-inc/nebula"
          target = "_blank"
      [[params.footer.company.links]]
          title = "新闻"
          link = "https://weibo.com/nebulagraph"
          target = "_blank"
      [[params.footer.company.links]]
          title = "联系"
          link = "https://www.linkedin.com/company/vesoft-nebula-graph/"
          target = "_blank"
      [[params.footer.company.links]]
          title = "招聘"
          link = "https://www.linkedin.com/company/vesoft-nebula-graph/"
          target = "_blank"
    
      [[params.footer.contactus]]
      title = "Contact Us"
      [[params.footer.contactus.links]]
          title = "(+86) 0571-28120658"
          link = ""
          pic = "iphone.png"
          target = "_blank"
      [[params.footer.contactus.links]]
          title = "info@vesoft.com"
          link = "mailto:info@vesoft.com"
          pic = "email.png"
          target = "_blank"
      [[params.footer.contactus.links]]
          title = "微信个人助理"
          link = ""
          pic = "weixin.png"
          id = "#myModal"
          target = "_blank"
  # About section
  # [params.advantage]
  #   headline    = "Why Nebula"
  #   description = "blablablabla..."

  # Service section
  [params.features]
        headline = "Nebula Graph 特性"

          [[params.features.list]]
            pic = "feature1.png"
            title = "开源"
            link = "https://discuss.nebula-graph.com.cn/"
            description1 = "我们致力于与"
            description2 = "社区合作"
            description3 = "普及及促进图数据库的发展。"
          
          [[params.features.list]]
            pic = "feature4.png"
            title = "安全"
            link = "https://nebula-graph.com.cn/posts/access-control-design-code-nebula-graph/"
            description1 = "具有基于角色的权限控制"
            description2 = "权限控制"
            description3 = "，授权才能访问。"

          [[params.features.list]]
            pic = "feature6.png"
            title = "扩展性"
            link = "https://nebula-graph.io/cn/posts/nebula-graph-storage-engine-overview/"
            description1 = "Nebula Graph 支持多种类型"
            description2 = "存储引擎。"
            description3 = "查询语言也可以拓展支持新的算法。"

          [[params.features.list]]
            pic = "feature2.png"
            title = "高性能"
            link = "https://discuss.nebula-graph.com.cn/t/topic/782/5"
            description1 = "Nebula Graph 在维持高吞吐量的同时依旧能做到"
            description2 = "低时延的读写。"

          [[params.features.list]]
            pic = "feature5.png"
            title = "扩容"
            link = "https://nebula-graph.io/cn/posts/nebula-graph-architecture-overview/"
            description1 = "基于shared-nothing"
            description2 = "分布式架构，"
            description3 = "Nebula Graph 支持线性扩容。"

          [[params.features.list]]
            pic = "feature3.png"
            title = "类SQL查询"
            link = "https://github.com/vesoft-inc/nebula/blob/master/docs/manual-CN/1.overview/1.concepts/2.nGQL-overview.md"
            description1 = "Nebula Graph的"
            description2 = "类 SQL 查询语言"
            description3 = "不仅易于理解，同时能满足各类复杂业务需求。"
          
          [[params.features.list]]
            pic = "feature8.png"
            link = "https://nebula-graph.io/cn/posts/introduction-to-snapshot-in-nebula-graph/"
            title = "高可用"
            description1 = "Nebula Graph 支持多种类型"
            description2 = "快照"
            description3 = "方式实现数据恢复，保证在局部失败的情况下服务的高可用性。"
 
          [[params.features.list]]
            pic = "feature7.png"
            title = "1.0 GA"
            link = "https://discuss.nebula-graph.com.cn/t/topic/789"
            description1 = "一线互联网大厂诸如京东、美团、小红书在生产环境使用 Nebula Graph，"
            description2 = "这是他们选择 Nebula Graph 的理由"
            description3 = "。"


  # [params.portfolio.modal]
  #       client = "Client"
  #       date = "Date"
  #       category = "Category"
  #       buttonText = "Close"
  # blog section
  [params.blog]
    title = "目录"

  # Tags
  [params.tags]
    title = "标签"
    all = "全部"
    pic = "LabelTagIcon.png"
  [[params.links]]
    text = "去 Github 点 star"
    link = "https://github.com/vesoft-inc/nebula"
    image = "/images/good.png"
    onclick = "gtag('event', 'Link Click', { event_category: 'Engagement', event_label: 'Star via sidebar'})"
  [[params.links]]
    text = "订阅 RSS"
    link = "https://nebula-graph.com.cn/posts/index.xml"
    image = "/images/rss.png"
    onclick = "gtag('event', 'Link Click', { event_category: 'Engagement', event_label: 'RSS on sidebar'})"
  [params.share]
    title = "分享"
  [params.rss]
    link = "https://nebula-graph.com.cn/posts/index.xml"

  # News section
  [params.news]
      pic = "download-cn.png"
      downloadLink = "/file/NebulaGraphMediaKit-CN.zip"
      title="媒体资源包"
      content1= "• 公司 Logo"
      content2= "• 创始人宣传照"
      [[params.news.list]]
        pic = "feature1.png"
        title = "开源图数据库研发商「欧若数网」开启全球商用化，获800万美元Pre-A轮融资"
        link = "https://36kr.com/p/737314527110281"
        date = "2020-06-05"
        source = "36kr"
        readMore = "Read More >>"
        Description = "图数据库研发商欧若数网科技有限公司（以下简称“欧若数网”）已完成 800 万美元 Pre-A 轮融资，由红点创投中国基金、经纬中国投资。本轮融资将主要用于最新产品 2.0 版本开发，以及全球市场拓展。"

      [[params.news.list]]
        pic = "feature4.png"
        title = "超大规模图数据库 Nebula Graph V1.0 发布，为数据分析处理提速"
        link = "http://software.it168.com/a2020/0609/6223/000006223679.shtml"
        date = "2020-06-09"
        source = "IT168"
        readMore = "Read More >>"
        Description = "分布式图数据库 Nebula Graph V1.0 正式亮相，为深耕 AI、金融、政府、医疗、IoT 等多个垂直领域的 CIO、架构师、数据科学家提供了新型的数据分析和洞察能力。"

  #  Real-time Recommendation section
  [params.realTimeRecommendation]
      pic = "realTimeRecommendation.png"
      bannerTtile = "实时推荐"
      bannerText="实时推荐是在线业务的新增长点，电商巨头亚马逊称其35%的销售额来自于商品交叉推荐。"
      [[params.realTimeRecommendation.fix]]
        title = "解决方案"
        btnText = "合作咨询"
        link = "mailto:sales@vesoft.com"
        [[params.realTimeRecommendation.fix.fixList]]
          text = "原生图存储保证高效、实时遍历高度关联的复杂数据 "
        [[params.realTimeRecommendation.fix.fixList]]
          text = "shared-nothing 的架构设计保证系统可扩展性"
      [[params.realTimeRecommendation.list]]
        pic = "realTimeRecommendationCase1.png"
        title = "商业目标"
        text = "为用户提供高度个性化的实时推荐，企业能够灵活添加推荐相关因子及数据源，提高推荐个性化程度。"
        calss = "left"
        background="backgroundA"

      [[params.realTimeRecommendation.list]]
        pic = "realTimeRecommendationCase2.png"
        title = "面临挑战"
        text = "要实现高度个性化的实时推荐，面临几个挑战："
        text1 = "1. 实时遍历高度关联的复杂数据"
        text2 = "2. 保证实时遍历查询性能"
        text3 = "3. 业务数据量迅速增加"
        calss = "right"
        background="backgroundB"
  
  #  Fraud Detection section
  [params.fraudDetection]
      pic = "fraudDetection.png"
      bannerTtile = "金融风控"
      bannerText="风险控制对金融行业的重要性不言而喻，其中层出不穷的金融欺诈手段对金融行业的健康发展造成了严重的威胁。"
      [[params.fraudDetection.fix]]
        title = "解决方案"
        btnText = "合作咨询"
        link = "mailto:sales@vesoft.com"
        [[params.fraudDetection.fix.fixList]]
          text = "原生图存储保证高效、实时遍历高度关联的复杂数据 "
        [[params.fraudDetection.fix.fixList]]
          text = "灵活的数据模型，新增业务逻辑不影响现有的逻辑"
        [[params.fraudDetection.fix.fixList]]
          text = "高可用，保障关键业务不断线"
      [[params.fraudDetection.list]]
        pic = "fraudDetection1.png"
        title = "商业目标"
        text = "通过分析交易行为识别欺诈交易特征，实现在交易中实时探测欺诈特征，阻断可疑交易。"
        calss = "left"
        background="backgroundA"

      [[params.fraudDetection.list]]
        pic = "fraudDetection2.png"
        title = "面临挑战"
        text = "要在金融交易发生的短时间内实时探测出可疑交易并返回结果，面临如下挑战："
        text1 = "1. 欺诈交易涉及的数据具有高度复杂的关联关系"
        text2 = "2. 保证实时遍历复杂关联数据的性能，在交易时间内返回分析结果"
        text3 = "3. 适应欺诈手段和规模的不断变迁"
        calss = "right"
        background="backgroundB"
  
  #  Cyber Security section
  [params.cyberSecurity]
      pic = "cyberSecurity.png"
      bannerTtile = "网络安全"
      bannerText="数据库是企业最为核心的数据保护对象，其中敏感信息保护、潜在威胁检测更是重中之重。"
      [[params.cyberSecurity.fix]]
        title = "解决方案"
        btnText = "合作咨询"
        link = "mailto:sales@vesoft.com"
        [[params.cyberSecurity.fix.fixList]]
          text = "原生图存储可快速遍历数据，了解事务之间隐藏关系 "
        [[params.cyberSecurity.fix.fixList]]
          text = "以集群维度创建快照，提供在线的数据备份功能、快速恢复"
      [[params.cyberSecurity.list]]
        pic = "cyberSecurity1.png"
        title = "商业目标"
        text = "通过跟踪网络和设备路径寻找潜在威胁，及时应对网络攻击。"
        calss = "left"
        background="backgroundA"

      [[params.cyberSecurity.list]]
        pic = "cyberSecurity2.png"
        title = "面临挑战"
        text = "要跟踪网络和设备路径寻找潜在攻击威胁，面临如下挑战："
        text1 = "1. 攻击路径存在复杂且隐蔽关系，传统防御手段难以有效识别"
        text2 = "2. 分析数据或基础设施是否遭受破坏需筛选海量数据"
        text3 = "3. 有组织的网络攻击可形成信息孤岛，需快速地判断单一事务是否为攻击的一环"
        calss = "right"
        background="backgroundB"

  # ai-and-machine-learning section
  [params.aiAndMachineLearning]
      pic = "aiAndMachineLearning1.png"
      bannerTtile = "知识图谱"
      bannerText="知识图谱广泛应用于聊天机器人、大数据风控、证券投资、智能医疗、自适应教育、推荐系统等场景，并覆盖泛互联网、金融、政务、医疗等众多领域。"
      [[params.aiAndMachineLearning.fix]]
        title = "解决方案"
        btnText = "合作咨询"
        link = "mailto:sales@vesoft.com"
        [[params.aiAndMachineLearning.fix.fixList]]
          text = "以属性图方式存储实体和实体间关系，提高知识图谱表达描述实际场景能力 "
        [[params.aiAndMachineLearning.fix.fixList]]
          text = "存储计算分离，资源独立扩展使资源利用更充分，便捷根据数据量进行扩缩容"
      [[params.aiAndMachineLearning.list]]
        pic = "aiAndMachineLearning2.png"
        title = "商业目标"
        text = "知识图谱的应用难点在于如何表达现实世界中千变万化的业务场景。"
        calss = "left"
        background="backgroundA"

      [[params.aiAndMachineLearning.list]]
        pic = "aiAndMachineLearning.png"
        title = "面临挑战"
        text = "要使用属性图表达多种业务场景，面临如下挑战："
        text1 = "1. 知识类型具有多样性，现实中实体及其之间存在复杂交错关系"
        text2 = "2. 海量数据的存储问题"
        calss = "right"
        background="backgroundB"
      