baseurl = "https://www-cdn.nebula-graph.com.cn/website/"
title = "Nebula Graph  - An Open Source, Distributed and High Performant Graph Database"
theme = "creative"
googleAnalytics = ""
DefaultContentLanguage = "cn"
defaultContentLanguageInSubdir = false

[languages]
################ init language Config ################
  [languages.default]
    contentDir = "content/cn"
