name:
on:
  push:
    branches:
      # - master
      - jerry-dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Github Action
      uses: actions/checkout@master

    - name: Setup ossutil
      run: wget http://gosspublic.alicdn.com/ossutil/1.6.15/ossutil64

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.65.3'

    - name: Build
      run: hugo --environment=chinese --minify -d nebula-website

    - name: Remove resource about chinese
      run: rm -rf ./nebula-website/en/

    - name: OSS UPLOAD
      run: |
        chmod 755 ossutil64 &&
        ossutil64 -c ./github/config/.ossutilconfig &&
        echo "ossutil ready" &&
        ossutil64 cp -r ./nebula-website/ oss://nebula-website-cn/website/ &&
        echo "oss upload finish"


    # - name: Compress
    #   run: tar -czf site.tar.gz nebula-website

    # - name: Transfer
    #   uses: appleboy/scp-action@master
    #   with:
    #       host: ${{ secrets.CN_HOST }}
    #       username: ${{ secrets.CN_USER_NAME }}
    #       password: ${{ secrets.CN_PASSWORD }}
    #       port: ${{ secrets.CN_PORT }}
    #       source: site.tar.gz 
    #       target: /usr/web

    # - name: UnCompress
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.CN_HOST }}
    #     username: ${{ secrets.CN_USER_NAME }}
    #     password: ${{ secrets.CN_PASSWORD }}
    #     port: ${{ secrets.CN_PORT }}
    #     script: tar -xzvf /usr/web/site.tar.gz -C /usr/web/